### ISSUE TITLE
apt remove redis doesn't uninstall redis-server 

### ISSUE THREAD

**Issue by gkorland** [redis/redis-debian#1]
Calling `apt remove redis` doesn't remove redis-server/redis-tools but only removes the package `redis`

```bash
$ sudo apt remove redis
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  redis-server redis-tools
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  redis
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 60.4 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 289992 files and directories currently installed.)
Removing redis (6:6.0.8-1rl1~focal1) ...
```

**Comment by yossigo** [comment]
@gkorland The `redis` package is a meta-package, it doesn't provide anything of its own but installs `redis-server` and `redis-tools`. What you describe is perfectly normal for Ubuntu/Debian meta-packages and can be addressed in two ways:

1. Use `apt install redis-server redis-tools` directly, and later remove them directly.
2. Use `apt autoremove` after removing the meta package.

There isn't really anything else to do from a POV of packaging.

**Comment by gkorland** [comment]
@yossigo I disagree, the bottom line user experience is not good, when I install a package I expect it clean after it self when I uninstall it

**Comment by yossigo** [comment]
@gkorland Do you have a suggestion how to improve this?
