### ISSUE TITLE
Version 6.2.7 missing from the PPA

### ISSUE THREAD

**Issue by Pyker** [redis/redis-debian#12]
This may be related to the action failing at https://github.com/redis/redis-debian/actions/runs/2233830788, but the 6.2.7 version is nowhere to be found in the PPA. There's 6.2.5, 6.2.6, and 7.0.0, but no 6.2.7: https://launchpad.net/~redislabs/+archive/ubuntu/redis

**Comment by yossigo** [comment]
@Pyker Thanks for reporting this, we'll take a look. Generally, we're trying to move away from the PPA and favor the official APT repository due to various limitations with PPA:

https://redis.io/docs/getting-started/installation/install-redis-on-linux/

**Comment by Pyker** [comment]
I eventually found the new repo, seems to work well. Thanks!

**Comment by yossigo** [comment]
I've updated the PPA description to indicate users should prefer the APT repository. At this point that's the best we can do, because the PPA does not support multiple versions of the same package.
