### ISSUE TITLE
No packages for bookworm

### ISSUE THREAD

**Issue by pluc** [redis/redis-debian#14]
This file does not exist: https://packages.redis.io/deb/dists/bookworm/InRelease

Which is what you try to access when you are under [bookworm](https://www.debian.org/releases/bookworm/) and follow the instructions mentioned [here](https://redis.io/docs/getting-started/installation/install-redis-on-linux/)

Solution is to [add bookworm](https://github.com/redis/redis-debian/blob/d10e0c14a368fbc79ee560cd27217269dc44e924/.github/workflows/apt.yml#L20) and do whatever other magic that needs to be done so that it builds on/for it.

Thanks!

**Comment by yossigo** [comment]
@pluc Thanks for reporting this, it's fixed now.
