### ISSUE TITLE
All packages other than 6.2.1 are no longer accessable from the PPA

### ISSUE THREAD

**Issue by onlyhavecans** [redis/redis-debian#6]
It seems all prior builds have been purged or hidden in launchpad, breaking our pins so we can verify the version before installing them. Even the latest 6.0.*, which was released recently, is gone.

Is there a reason for this? is this a policy from now on?

**Comment by yossigo** [comment]
@onlyhavecans This is done by Launchpad and AFAIK there's no way around that. It's a big problem indeed, we hope to migrate to a standalone apt repo as soon as we got some bandwidth for that project.

**Comment by yossigo** [comment]
Standalone APT repository is now available and should address this issue from now on:
https://redis.io/download#from-the-official-debianubuntu-apt-repository-beta
