### ISSUE TITLE
[Question] How to install the latest redis packages in debian 9(stretch) or debian 10(buster)

### ISSUE THREAD

**Issue by rahulsadanandan** [redis/redis-debian#7]
I see the packages here ->
https://launchpad.net/~redislabs/+archive/ubuntu/redis/+packages
are for ubuntu distributions. 

I tried to install these packages in Debian 9 (stretch) as their official repo has an older version of Redis.
 
https://launchpad.net/~redislabs/+archive/ubuntu/redis/+files/redis-tools_6.2.3-1rl1~xenial1_amd64.deb
https://launchpad.net/~redislabs/+archive/ubuntu/redis/+files/redis-server_6.2.3-1rl1~xenial1_amd64.deb

but this may run into some dependency problems.

Earlier we used the packages (derived from work done by Chris Lea.)
https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server/+packages.  (Redis updated till 6.0.6)
https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server/+files/redis-tools_6.0.6-3chl1~xenial1_amd64.deb
https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server/+files/redis-server_6.0.6-3chl1~xenial1_amd64.deb

which worked well across distros without any dependency problems (ubuntu, debian9, debian10 etc)
Is there any other source from where we can get the latest Redis(6.2.x) deb package for Debian (9 and 10). 

Thanks

**Comment by yossigo** [comment]
@rahulsadanandan Unfortunately, not at the moment. Ideally we want to have a dedicated apt repo which will also solve other issues but so far haven't had the bandwidth to do that.

What dependencies issues do you see? If 6.0.6 used to work this could be a regression we can somehow address.

**Comment by rahulsadanandan** [comment]
@yossigo Thanks for the update

here are the dependencies issues that I found

Debian 9 stretch
https://launchpad.net/~redislabs/+archive/ubuntu/redis/+files/redis-tools_6.2.3-1rl1~xenial1_amd64.deb
 (dpkg -i redis-tools_6.2.3-1rl1~xenial1_amd64.deb)

` redis-tools depends on libssl1.0.0 (>= 1.0.0); however:
  Package libssl1.0.0 is not installed.`
  
  we don’t have the right package in debian 9 repo
  https://packages.debian.org/stretch/libssl1.0.2
  
  even if i install libssl1.0.2 it still fails with the same error.

**Comment by yossigo** [comment]
@rahulsadanandan I've just tested the bionic build on Debian 10 and it seems to install fine.

Comparing the redis-tools_6.0.6-3chl1~xenial1_amd64.deb control file with the latest one I see both depend on `libssl1.0.0 (>= 1.0.0)` so I'm not sure what seems to be the problem. I do see an additional `libsystemd0` dependency though.

**Comment by yossigo** [comment]
@rahulsadanandan We've set up a dedicated apt repository now, with direct support for Debian stretch and buster. It's still not officially announced as we want to do some testing first, but will be happy to get any feedback on that.

To use it:
```
curl https://packages.redis.io/gpg | sudo apt-key add -
echo 'deb https://packages.redis.io/deb <your-distro> main' | sudo tee /etc/apt/sources.list.d/redis.list
apt-get update
apt-get install -V redis
```

**Comment by rahulsadanandan** [comment]
@yossigo Thanks, we will check this and provide feedback.
