### ISSUE TITLE
Latest available version for debian 10?

### ISSUE THREAD

**Issue by rightaway** [redis/redis-debian#9]
I see there's no official apt repository for this. Is there a timeline on when we can expect it? Most other database products maintain official, up to date repositories for most major operating systems (especially debian) but redis doesn't.

What's the latest version of redis we can use for debian 10 and how do we install it? Is there a 3rd party repository that can be used in the meantime?

**Comment by yossigo** [comment]
@rightaway Currently there isn't an official apt repository, but it's definitely high on our list. I think the closest thing you can get at the moment is the upstream Debian package from stable-bpo or testing.

**Comment by rightaway** [comment]
Anything we can do to help?

Even debian 11 will only have redis 6.0 in its official repo and the latest is already newer than that so there's no official way to use the latest stable redis on debian.

**Comment by yossigo** [comment]
@rightaway I've just tested the Launchpad packages (https://launchpad.net/~redislabs/+archive/ubuntu/redis) and they seem to install fine on Debian 10. I've successfully used the `bionic` package.

Ideally I'd like to move forward with an apt (and eventually yum) repository. To keep things transparent and secure, I want to use GitHub Actions directly. We already have workflows in place to build and sign the source dpkg, but we still need:

* Binary build steps for all major Ubuntu and Debian versions on amd/i386/arm64/armhf, probably using qemu-deboostrap.
* Publishing to an S3 based repository.

I was hoping to find some of this already available but could not find it.

**Comment by rightaway** [comment]
For the apt repo would you consider the binary build steps for amd64 first since that's probably far more common than the other ones? Could at least get it out there and people trying it.

**Comment by yossigo** [comment]
@rightaway I've set up an **experimental** build process and APT repository. Haven't had much time yet to test this thoroughly, but you can take a look - some testing and feedback will be very much appreciated. To set it up:

```
curl http://packages.redis.io/gpg | sudo apt-key add -
echo 'deb http://packages.redis.io/deb <your-distro> main' | sudo tee /etc/apt/sources.list.d/redis.list
apt-get update
apt-get install -V redis
```

Packages should be available for stretch, buster, xenial, bionic, focal, hirsute, groovy and for i386, amd64, arm64 and armhf (at least where the arch/dist matrix is supported).

**Comment by rightaway** [comment]
Would be great if both links could be available as https.

**Comment by yossigo** [comment]
@rightaway Both are now available as https as well. Curiously most distros are still on http, I suppose the assumption is that's safe enough given that keys are preloaded and the repo is signed.

**Comment by amelie-webedia** [comment]
Install on debian buster work like a charm, thank you very much @yossigo :)

**Comment by yossigo** [comment]
Thanks @amelie-webedia, closing this issue as the problem seems to be resolved now.
